"""Security utilities"""
import base64
import hmac
import hashlib
import json
import secrets
from datetime import timedelta
from typing import Optional

try:  # pragma: no cover - optional dependency fallback
    from jose import JWTError, jwt
except ImportError:  # pragma: no cover - exercised in lightweight test environments
    class JWTError(Exception):
        """Fallback JWT error used when python-jose is unavailable."""


    class _FallbackJWT:
        """Minimal JWT-like encoder/decoder for non-auth test environments."""

        @staticmethod
        def encode(payload: dict, key: str, algorithm: str = "HS256") -> str:
            del key, algorithm
            raw = json.dumps(payload, default=str).encode("utf-8")
            return base64.urlsafe_b64encode(raw).decode("utf-8")

        @staticmethod
        def decode(token: str, key: str, algorithms: list[str] | None = None) -> dict:
            del key, algorithms
            try:
                padding = "=" * (-len(token) % 4)
                raw = base64.urlsafe_b64decode(f"{token}{padding}".encode("utf-8"))
                return json.loads(raw.decode("utf-8"))
            except Exception as exc:  # pragma: no cover - fallback error path
                raise JWTError(str(exc)) from exc


    jwt = _FallbackJWT()

try:  # pragma: no cover - optional dependency fallback
    from passlib.context import CryptContext
except ImportError:  # pragma: no cover - exercised in lightweight test environments
    class CryptContext:  # type: ignore[override]
        """Minimal hashing fallback used when passlib is unavailable."""

        def __init__(self, schemes: list[str] | None = None, deprecated: str = "auto"):
            del schemes, deprecated

        def hash(self, password: str) -> str:
            return hashlib.sha256(password.encode("utf-8")).hexdigest()

        def verify(self, plain_password: str, hashed_password: str) -> bool:
            return self.hash(plain_password) == hashed_password

try:  # pragma: no cover - optional dependency fallback
    import bcrypt as bcrypt_backend
except ImportError:  # pragma: no cover - exercised in lightweight test environments
    bcrypt_backend = None

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.database import get_db
from app.core.time import utc_now
from app.models.models import User

CANONICAL_OPERATOR_USERNAME = "operator"

PBKDF2_SCHEME = "pbkdf2_sha256"
_PBKDF2_ROUNDS = 390000
_PBKDF2_PREFIX = "$pbkdf2-sha256$"

pwd_context = CryptContext(schemes=[PBKDF2_SCHEME, "bcrypt"], deprecated="auto")
bearer_scheme = HTTPBearer(auto_error=False)


def _hash_pbkdf2_password(password: str, *, salt: str | None = None, rounds: int = _PBKDF2_ROUNDS) -> str:
    """Generate a portable PBKDF2-SHA256 hash without depending on passlib backends."""
    normalized_salt = salt or secrets.token_urlsafe(16)
    derived_key = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        normalized_salt.encode("utf-8"),
        rounds,
    )
    checksum = base64.urlsafe_b64encode(derived_key).decode("ascii").rstrip("=")
    return f"{_PBKDF2_PREFIX}{rounds}${normalized_salt}${checksum}"


def _is_pbkdf2_hash(hashed_password: str) -> bool:
    """Return whether the stored hash uses the repository's PBKDF2 prefix."""
    return hashed_password.startswith(_PBKDF2_PREFIX)


def _verify_pbkdf2_password(plain_password: str, hashed_password: str) -> bool:
    """Verify PBKDF2 hashes generated by this application without passlib."""
    if not _is_pbkdf2_hash(hashed_password):
        return False

    try:
        _, _, rounds_raw, salt, checksum = hashed_password.split("$", 4)
        rounds = int(rounds_raw)
    except (TypeError, ValueError):
        return False

    expected_hash = _hash_pbkdf2_password(plain_password, salt=salt, rounds=rounds)
    return hmac.compare_digest(expected_hash, hashed_password)


def _is_legacy_bcrypt_hash(hashed_password: str) -> bool:
    """Return whether the stored hash uses bcrypt's modular crypt format."""
    return hashed_password.startswith("$2")


def _is_legacy_sha256_hash(hashed_password: str) -> bool:
    """Return whether the stored hash looks like the old sha256 fallback format."""
    normalized = hashed_password.lower()
    return len(normalized) == 64 and all(character in "0123456789abcdef" for character in normalized)


def _verify_legacy_bcrypt_password(plain_password: str, hashed_password: str) -> bool:
    """Verify legacy bcrypt hashes without relying on passlib's backend auto-detection."""
    if bcrypt_backend is None or not _is_legacy_bcrypt_hash(hashed_password):
        return False

    try:
        return bcrypt_backend.checkpw(plain_password.encode("utf-8"), hashed_password.encode("utf-8"))
    except (TypeError, ValueError):
        return False


def _verify_legacy_sha256_password(plain_password: str, hashed_password: str) -> bool:
    """Verify hashes created by the previous lightweight sha256-only fallback."""
    if not _is_legacy_sha256_hash(hashed_password):
        return False

    expected_hash = hashlib.sha256(plain_password.encode("utf-8")).hexdigest()
    return hmac.compare_digest(expected_hash, hashed_password)


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify password"""
    try:
        if pwd_context.verify(plain_password, hashed_password):
            return True
    except Exception:  # pragma: no cover - backend incompatibilities vary by runtime image
        pass

    if _verify_pbkdf2_password(plain_password, hashed_password):
        return True

    return _verify_legacy_bcrypt_password(plain_password, hashed_password) or _verify_legacy_sha256_password(
        plain_password,
        hashed_password,
    )


def get_password_hash(password: str) -> str:
    """Hash password"""
    return _hash_pbkdf2_password(password)


def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    """Create JWT access token"""
    to_encode = data.copy()
    if expires_delta:
        expire = utc_now() + expires_delta
    else:
        expire = utc_now() + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)

    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, settings.JWT_SECRET_KEY, algorithm=settings.JWT_ALGORITHM)
    return encoded_jwt


def verify_token(token: str) -> Optional[dict]:
    """Verify JWT token"""
    try:
        payload = jwt.decode(token, settings.JWT_SECRET_KEY, algorithms=[settings.JWT_ALGORITHM])
        return payload
    except JWTError:
        return None


def get_current_operator_from_bearer(
    credentials: HTTPAuthorizationCredentials | None = Depends(bearer_scheme),
    db: Session = Depends(get_db),
) -> User:
    """Validate a dashboard Bearer token and return the active singleton operator."""
    if credentials is None or credentials.scheme.lower() != "bearer":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing bearer token",
            headers={"WWW-Authenticate": "Bearer"},
        )

    token_payload = verify_token(credentials.credentials)
    if not token_payload or token_payload.get("type") != "access":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid bearer token",
            headers={"WWW-Authenticate": "Bearer"},
        )

    try:
        operator_id = int(token_payload.get("sub"))
    except (TypeError, ValueError) as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token subject",
            headers={"WWW-Authenticate": "Bearer"},
        ) from exc

    operator = db.query(User).filter(User.id == operator_id).first()
    if operator is None or not operator.is_active:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Operator is not active",
            headers={"WWW-Authenticate": "Bearer"},
        )

    return operator


def get_current_operator_optional(
    credentials: HTTPAuthorizationCredentials | None = Depends(bearer_scheme),
    db: Session = Depends(get_db),
) -> User | None:
    """Return the bearer-token operator when supplied, else ``None``.

    Used by endpoints that historically allowed unauthenticated access but now
    want to layer per-operator scoping on top when a bearer is present.
    Invalid/expired tokens still raise ``401`` so misconfigured clients fail
    loudly instead of silently falling back.
    """
    if credentials is None or credentials.scheme.lower() != "bearer":
        return None
    return get_current_operator_from_bearer(credentials=credentials, db=db)


def is_privileged_operator(operator: User) -> bool:
    """Return whether the operator can act on behalf of other operator accounts.

    The canonical ``operator`` account (single-user mode) and any admin-flagged
    account are allowed to fetch dashboard/analytics payloads scoped to other
    operator IDs (e.g. synthetic-* companies).
    """
    return bool(
        getattr(operator, "is_admin", False)
        or operator.username == CANONICAL_OPERATOR_USERNAME
    )


def resolve_target_operator(
    db: Session,
    current: User,
    target_id: Optional[int],
) -> User:
    """Resolve which operator a dashboard/analytics request should target.

    - ``target_id`` is ``None``  -> return ``current`` (bearer-token owner).
    - ``target_id`` matches ``current.id`` -> return ``current``.
    - Otherwise: only canonical ``operator`` accounts and admins may target
      another operator. Unknown ids return ``404``; unauthorized cross-account
      access returns ``403``.
    """
    if target_id is None or int(target_id) == int(current.id):
        return current

    if not is_privileged_operator(current):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not authorized to view another operator's data",
        )

    target = db.query(User).filter(User.id == int(target_id)).first()
    if target is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Operator not found",
        )
    return target
